-- Run this SQL in your Supabase SQL Editor
-- Go to: https://ilmwebrpykhijzkxfimc.supabase.co/project/default/sql

-- Create app_users table
CREATE TABLE IF NOT EXISTS app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_app_users_username ON app_users(username);

-- Enable RLS (Row Level Security)
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can read own data" ON app_users;
DROP POLICY IF EXISTS "Users can insert own data" ON app_users;
DROP POLICY IF EXISTS "Users can update own data" ON app_users;

-- Create policies for authentication
CREATE POLICY "Users can read own data" ON app_users
  FOR SELECT USING (auth.uid()::text = username::text);

CREATE POLICY "Users can insert own data" ON app_users
  FOR INSERT WITH CHECK (auth.uid()::text = username::text);

CREATE POLICY "Users can update own data" ON app_users
  FOR UPDATE USING (auth.uid()::text = username::text);

-- Allow service role to manage users (for backend)
CREATE POLICY "Service role can manage users" ON app_users
  FOR ALL USING (auth.role() = 'service_role');

-- Test the table
SELECT 'app_users table created successfully' as result;
