import json
import requests
from typing import Optional, Dict, List
from app.settings import settings

class GeminiService:
    def __init__(self):
        self.api_key = settings.gemini_api_key
        self.base_url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
    
    def generate_content(self, prompt: str, temperature: float = 0.7, max_tokens: int = 1000) -> Optional[str]:
        """Generate content using Google Gemini API"""
        if not self.api_key:
            print("Gemini API key not configured")
            return None
        
        try:
            headers = {
                "Content-Type": "application/json",
            }
            
            data = {
                "contents": [{
                    "parts": [{
                        "text": prompt
                    }]
                }],
                "generationConfig": {
                    "temperature": temperature,
                    "maxOutputTokens": max_tokens,
                    "topK": 40,
                    "topP": 0.95,
                }
            }
            
            url = f"{self.base_url}?key={self.api_key}"
            
            response = requests.post(url, headers=headers, json=data, timeout=30)
            
            if response.status_code == 200:
                result = response.json()
                if "candidates" in result and len(result["candidates"]) > 0:
                    content = result["candidates"][0]["content"]["parts"][0]["text"]
                    # Remove markdown code blocks if present
                    if content.startswith("```json"):
                        content = content.replace("```json", "").replace("```", "").strip()
                    elif content.startswith("```"):
                        content = content.replace("```", "").strip()
                    return content
                else:
                    print("No content generated by Gemini")
                    return None
            else:
                print(f"Gemini API error: {response.status_code} - {response.text}")
                return None
                
        except Exception as e:
            print(f"Gemini service error: {e}")
            return None
    
    def generate_quiz_questions(self, domain: str, difficulty: str, num_questions: int = 5) -> Optional[List[Dict]]:
        """Generate quiz questions using Gemini"""
        prompt = f"""
        Generate {num_questions} multiple-choice questions for {domain} at {difficulty} level.
        
        Return the response as a JSON array with this exact format:
        [
            {{
                "question": "Clear question text here",
                "options": ["Option A", "Option B", "Option C", "Option D"],
                "correct_answer": 0,
                "explanation": "Brief explanation of why this answer is correct"
            }}
        ]
        
        Requirements:
        1. Questions must be relevant to {domain}
        2. Difficulty must match {difficulty} level
        3. Only one correct answer per question (0-based index: 0, 1, 2, or 3)
        4. Provide educational explanations
        5. Make questions practical and realistic
        """
        
        content = self.generate_content(prompt, temperature=0.7, max_tokens=2000)
        
        if content:
            try:
                # Try to parse as JSON
                questions_data = json.loads(content)
                return questions_data
            except json.JSONDecodeError:
                print("Failed to parse Gemini response as JSON")
                # Try to extract JSON from the response
                import re
                json_match = re.search(r'\[.*\]', content, re.DOTALL)
                if json_match:
                    try:
                        questions_data = json.loads(json_match.group(0))
                        return questions_data
                    except:
                        pass
        
        return None
    
    def analyze_resume(self, text: str) -> Optional[Dict]:
        """Analyze resume using Gemini"""
        prompt = f"""
        Analyze this resume text and provide detailed insights:
        
        {text[:2000]}
        
        Return a JSON response with this exact format:
        {{
            "enhanced_skills": ["skill1", "skill2", "skill3"],
            "experience_level": "Entry/Mid/Senior/Executive",
            "strengths": ["strength1", "strength2", "strength3"],
            "improvements": ["improvement1", "improvement2", "improvement3"],
            "recommended_roles": ["role1", "role2", "role3"],
            "ai_score": 85
        }}
        
        Be professional and constructive in your analysis.
        """
        
        content = self.generate_content(prompt, temperature=0.3, max_tokens=1000)
        
        if content:
            try:
                analysis = json.loads(content)
                return analysis
            except json.JSONDecodeError:
                print("Failed to parse Gemini resume analysis as JSON")
        
        return None
    
    def generate_job_recommendations(self, keywords: str, location: str, job_type: str, experience_level: str) -> Optional[List[Dict]]:
        """Generate job recommendations using Gemini"""
        prompt = f"""
        Generate 5 realistic job recommendations for:
        Keywords: {keywords}
        Location: {location}
        Job Type: {job_type}
        Experience Level: {experience_level}
        
        Return JSON with this exact format:
        [
            {{
                "title": "Job Title",
                "company": "Company Name",
                "location": "Location",
                "description": "Brief job description",
                "requirements": ["req1", "req2", "req3"],
                "match_score": 85
            }}
        ]
        
        Make jobs realistic and relevant to the keywords. Use real company names when possible.
        """
        
        content = self.generate_content(prompt, temperature=0.7, max_tokens=1500)
        
        if content:
            try:
                jobs_data = json.loads(content)
                return jobs_data
            except json.JSONDecodeError:
                print("Failed to parse Gemini job recommendations as JSON")
        
        return None
    
    def enhance_job_analysis(self, job_title: str, job_description: str, keywords: str) -> Optional[Dict]:
        """Enhance job analysis using Gemini"""
        prompt = f"""
        Analyze this job listing for a candidate looking for "{keywords}" positions:
        
        Title: {job_title}
        Description: {job_description[:300]}...
        
        Return JSON with this exact format:
        {{
            "enhanced_score": 85,
            "key_requirements": ["req1", "req2", "req3"],
            "match_reason": "Brief explanation of why this matches"
        }}
        """
        
        content = self.generate_content(prompt, temperature=0.3, max_tokens=300)
        
        if content:
            try:
                analysis = json.loads(content)
                return analysis
            except json.JSONDecodeError:
                print("Failed to parse Gemini job enhancement as JSON")
        
        return None

# Global Gemini service instance
gemini_service = GeminiService()
